export const DND_5E_DEFAULT_DATA = {
  class: '',
  level: 1,
  race: '',
  background: '',
  alignment: '',
  xp: 0,
  hp: { current: 10, max: 10, temp: 0 },
  ca: 10,
  speed: '',
  initiative: '',
  inspiration: false,
  proficiencyBonus: '+2',
  passivePerception: 10,
  deathSaves: { success: 0, failure: 0 },
  hitDice: { total: '', current: 0 },
  attributes: [
    { name: 'FOR', value: 10, mod: '+0', save: false },
    { name: 'DES', value: 10, mod: '+0', save: false },
    { name: 'CON', value: 10, mod: '+0', save: false },
    { name: 'INT', value: 10, mod: '+0', save: false },
    { name: 'SAB', value: 10, mod: '+0', save: false },
    { name: 'CAR', value: 10, mod: '+0', save: false },
  ],
  skills: [
    { name: 'Acrobacia', attr: 'DES', mod: '+0', proficient: false },
    { name: 'Adestrar Animais', attr: 'SAB', mod: '+0', proficient: false },
    { name: 'Arcanismo', attr: 'INT', mod: '+0', proficient: false },
    { name: 'Atletismo', attr: 'FOR', mod: '+0', proficient: false },
    { name: 'Atuação', attr: 'CAR', mod: '+0', proficient: false },
    { name: 'Enganação', attr: 'CAR', mod: '+0', proficient: false },
    { name: 'Furtividade', attr: 'DES', mod: '+0', proficient: false },
    { name: 'História', attr: 'INT', mod: '+0', proficient: false },
    { name: 'Intimidação', attr: 'CAR', mod: '+0', proficient: false },
    { name: 'Intuição', attr: 'SAB', mod: '+0', proficient: false },
    { name: 'Investigação', attr: 'INT', mod: '+0', proficient: false },
    { name: 'Medicina', attr: 'SAB', mod: '+0', proficient: false },
    { name: 'Natureza', attr: 'INT', mod: '+0', proficient: false },
    { name: 'Percepção', attr: 'SAB', mod: '+0', proficient: false },
    { name: 'Persuasão', attr: 'CAR', mod: '+0', proficient: false },
    { name: 'Prestidigitação', attr: 'DES', mod: '+0', proficient: false },
    { name: 'Religião', attr: 'INT', mod: '+0', proficient: false },
    { name: 'Sobrevivência', attr: 'SAB', mod: '+0', proficient: false },
  ],
  attacks: [],
  equipment: '',
  features: '',
  spellcasting: {
    ability: '',
    saveDC: 8,
    attackBonus: '+0',
    slots: [
      { level: 1, total: 0, used: 0 },
      { level: 2, total: 0, used: 0 },
      { level: 3, total: 0, used: 0 },
    ],
    spells: []
  }
};
